apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - products-deployment.yaml
  - products-service.yaml
images:
  - name: products-service
    newName: ghcr.io/abdelkaderbenhmida/products-service
    newTag: latest
