#!/usr/bin/env python3
"""Generate requirements-hashed.txt offline.

The build box cannot reach PyPI, but every wheel the environment was
installed from is still in pip's http-v2 content cache. This script:
  1. walks the cache, sniffing zips to recover (name, version, wheel);
  2. computes the dependency closure of controlplane/requirements.txt
     from the installed distributions' METADATA (markers evaluated
     for this interpreter), with [extra] deps included;
  3. writes pin + sha256 per wheel to requirements-hashed.txt.
"""

import hashlib
import re
import sys
import zipfile
from pathlib import Path
from packaging.markers import Marker
from packaging.requirements import Requirement

CACHE = Path.home() / ".cache/pip/http-v2"
OUT = Path("controlplane/requirements-hashed.txt")


def _canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def sniff_wheels(cache: Path):
    wheels = {}
    for body in cache.rglob("*.body"):
        try:
            with zipfile.ZipFile(body) as zf:
                names = [n for n in zf.namelist() if n.endswith("WHEEL")]
                if not names:
                    continue
                meta = [n for n in zf.namelist() if n.endswith(".dist-info/METADATA")]
                if not meta:
                    continue
                text = zf.read(meta[0]).decode("utf-8", "replace")
                name = _canon(re.search(r"^Name: (.+)$", text, re.M).group(1))
                raw_dist = re.search(r"^Name: (.+)$", text, re.M).group(1).replace("-", "_")
                version = re.search(r"^Version: (.+)$", text, re.M).group(1)
                wheel_text = zf.read(names[0]).decode("utf-8", "replace")
                tags = re.findall(r"^Tag: (.+)$", wheel_text, re.M) or ["py3-none-any"]
                parts = [t.split("-") for t in tags]
                compressed = ".".join(sorted({p[0] for p in parts})) + "-" + ".".join(
                    sorted({p[1] for p in parts})
                ) + "-" + ".".join(sorted({p[2] for p in parts}))
                wheels.setdefault(name, []).append(
                    (version, compressed, raw_dist, body)
                )
        except (zipfile.BadZipFile, OSError, AttributeError):
            continue
    return wheels


def closure(requirements_txt: Path):
    """Resolve the pinned runtime closure via installed METADATA."""
    import importlib.metadata as md

    top = []
    extras = {}
    for line in requirements_txt.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        req = Requirement(line)
        top.append(_canon(req.name))
        if req.extras:
            extras.setdefault(_canon(req.name), set()).update(req.extras)

    dists = {_canon(d.metadata["Name"]): d for d in md.distributions()}
    seen = set()
    pending = [(name, [f"extra == {e!r}" for e in extras.get(name, ())]) for name in top]
    resolved = {}
    while pending:
        name, extra_markers = pending.pop(0)
        name = _canon(name)
        if name in seen:
            continue
        dist = dists.get(name)
        if dist is None:
            raise SystemExit(f"missing installed dist for {name}")
        seen.add(name)
        resolved[name] = dist.metadata["Version"]
        for req_str in dist.requires or ():
            if "extra" in req_str and not any(
                Marker(m).evaluate() for m in extra_markers
            ):
                continue
            req = Requirement(req_str)
            if req.marker and not req.marker.evaluate():
                continue
            pending.append((_canon(req.name), list(extra_markers)))
    return top, resolved


def main() -> int:
    wheels = sniff_wheels(CACHE)
    if not wheels:
        print("no wheels found in pip cache", file=sys.stderr)
        return 1
    top, resolved = closure(Path("controlplane/requirements.txt"))
    missing = sorted(set(resolved) - set(wheels))
    if missing:
        print("missing cached wheels:", ", ".join(missing), file=sys.stderr)
        return 1
    lines = []
    for name in top:
        body = _pick(wheels, name, resolved[name])
        digest = hashlib.sha256(body.read_bytes()).hexdigest()
        lines.append(f"{name}=={resolved[name]} \\")
        lines.append(f"    --hash=sha256:{digest}")
    for name in sorted(set(resolved) - set(top)):
        body = _pick(wheels, name, resolved[name])
        digest = hashlib.sha256(body.read_bytes()).hexdigest()
        lines.append(f"{name}=={resolved[name]} \\")
        lines.append(f"    --hash=sha256:{digest}")
    OUT.write_text(
        "# Generated by scripts/hash-requirements.py — regenerate, never edit by hand.\n"
        + "\n".join(lines)
        + "\n"
    )
    print(f"wrote {OUT} ({len(resolved)} packages)")
    return 0


def _pick(wheels, name, version):
    for cand_version, _tag, _raw, body in wheels.get(name, ()):
        if cand_version == version:
            return body
    print(f"no cached wheel matching installed {name}=={version}", file=sys.stderr)
    sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) == 3 and sys.argv[1] == "--debug-name":
        wheels = sniff_wheels(CACHE)
        for version, tag, raw_dist, body in wheels.get(_canon(sys.argv[2]), ()):
            print(version, tag, raw_dist, body.stat().st_size)
        sys.exit(0)
    if len(sys.argv) == 3 and sys.argv[1] == "--extract-dir":
        import shutil

        resolved = {}
        for line in Path("controlplane/requirements-hashed.txt").read_text().splitlines():
            line = line.strip().rstrip("\\").strip()
            if line and not line.startswith(("#", "--hash")):
                pkg, ver = line.split("==")
                resolved[pkg] = ver
        out = Path(sys.argv[2])
        out.mkdir(parents=True, exist_ok=True)
        wheels = sniff_wheels(CACHE)
        for pkg, ver in resolved.items():
            _v, tag, raw_dist, body = next(
                (c, t, r, b) for c, t, r, b in wheels.get(pkg, ()) if c == ver
            )
            filename = f"{raw_dist}-{ver}-{tag}.whl"
            shutil.copy(body, out / filename)
        print(f"extracted {len(resolved)} wheels to {out}")
        sys.exit(0)
    sys.exit(main())