#!/usr/bin/env bash
# Stand up the Vault the control plane stores tenant secrets in.
#
# Without it, `get_secret_store()` falls back to DevSecretStore — values kept
# as plaintext in Redis. That is tolerable for an SSH key generated by the
# platform itself, and not tolerable for a tenant's git token, which is a
# credential to their private source that they handed us. The credential API
# refuses to store one outside development when no Vault is configured.
#
# This runs Vault in dev mode: in-memory storage, auto-unsealed, one known
# root token. That is right for a laptop and wrong for anything else — dev
# mode loses every secret on restart and the root token is not a secret at
# all. For a real deployment use k8s/vault/manifests.yaml, which runs a sealed
# server with Kubernetes auth.
#
# Env:
#   VAULT_NAME    container name        (default controlplane-vault)
#   VAULT_PORT    host port             (default 8200)
#   VAULT_TOKEN   dev root token        (default controlplane-dev-root)
set -euo pipefail

VAULT_NAME="${VAULT_NAME:-controlplane-vault}"
VAULT_PORT="${VAULT_PORT:-8200}"
VAULT_TOKEN="${VAULT_TOKEN:-controlplane-dev-root}"

command -v docker >/dev/null || { echo "docker not found on PATH" >&2; exit 1; }

if [ "$(docker inspect -f '{{.State.Running}}' "$VAULT_NAME" 2>/dev/null || true)" != "true" ]; then
  docker rm -f "$VAULT_NAME" >/dev/null 2>&1 || true
  docker run -d --name "$VAULT_NAME" \
    --cap-add=IPC_LOCK \
    -p "127.0.0.1:${VAULT_PORT}:8200" \
    -e "VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}" \
    -e "VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200" \
    hashicorp/vault:latest >/dev/null
  echo "started ${VAULT_NAME} on 127.0.0.1:${VAULT_PORT}"
else
  echo "${VAULT_NAME} already running"
fi

# Wait for it to answer before anyone tries to write a secret.
for _ in $(seq 1 30); do
  if curl -sf "http://127.0.0.1:${VAULT_PORT}/v1/sys/health" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

if ! curl -sf "http://127.0.0.1:${VAULT_PORT}/v1/sys/health" >/dev/null 2>&1; then
  echo "vault did not become healthy" >&2
  exit 1
fi

# Dev mode mounts kv-v2 at secret/ already; creating it again is an error, so
# only mount it if it is missing (which it is on a non-dev server).
if ! curl -sf -H "X-Vault-Token: ${VAULT_TOKEN}" \
     "http://127.0.0.1:${VAULT_PORT}/v1/sys/mounts" | grep -q '"secret/"'; then
  curl -sf -X POST -H "X-Vault-Token: ${VAULT_TOKEN}" \
    -d '{"type":"kv","options":{"version":"2"}}' \
    "http://127.0.0.1:${VAULT_PORT}/v1/sys/mounts/secret" >/dev/null
  echo "mounted kv-v2 at secret/"
fi

cat <<EOF

vault ready. Export these for the API and the worker, then restart both:

  export VAULT_ADDR=http://127.0.0.1:${VAULT_PORT}
  export VAULT_TOKEN=${VAULT_TOKEN}

Dev mode keeps secrets in memory: restarting the container discards every
stored credential and tenants must re-enter their git tokens.
EOF
