apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-base
  namespace: argocd
  labels:
    app.kubernetes.io/name: observability-base
    app.kubernetes.io/part-of: devops-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: devops-platform
  source:
    repoURL: https://github.com/abdelkaderbenhmida/stage.git
    targetRevision: secondary
    path: k8s/monitoring/base
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
