# -*- coding: utf-8 -*-
"""Titre et sous-titre affiches dans la barre de chaque figure terminal."""

TITRES = {
# ---------- cluster ----------
"k8s-clusterinfo":        ("Kubernetes — État du cluster", "API server et versions client / serveur"),
"k8s-controlplane-pods":  ("Kubernetes — Plan de contrôle", "etcd, API server, scheduler, controller-manager, CoreDNS"),
"k8s-nodes-wide":         ("Kubernetes — Nœuds", "version kubelet, runtime, adresses internes"),
"namespaces-psa":         ("Kubernetes — Namespaces", "étiquettes Pod Security Admission"),
"guide-etat-sain":        ("Plateforme — Carte d'identité", "consommation des nœuds et répartition des pods"),
"k8s-limitrange-quota":   ("Kubernetes — LimitRange et ResourceQuota", "plafonds du namespace devops-platform"),
"k8s-netpol-list":        ("Kubernetes — NetworkPolicies", "politiques réseau du namespace applicatif"),
"k8s-netpol-deny-proof":  ("Kubernetes — Preuve du default-deny", "trafic refusé hors namespace, autorisé à l'intérieur"),
"k8s-hpa-status":         ("Kubernetes — HorizontalPodAutoscaler", "cibles CPU et mémoire des cinq services"),
"k8s-pdb":                ("Kubernetes — PodDisruptionBudget", "disponibilité minimale garantie"),
"k8s-securitycontext":    ("Kubernetes — Security Context", "runAsNonRoot, seccomp, capabilities"),
"k8s-rolling-update":     ("Kubernetes — Mise à jour progressive", "maxSurge et maxUnavailable en action"),
"k8s-calico-connectivity": ("Kubernetes — Connectivité réseau", "résolution DNS et appel inter-pods"),
"kustomize-prod-render":  ("Kustomize — Rendu de l'overlay prod", "namespace, répliques et images"),
"overlays-diff-devprod":  ("Kustomize — Comparaison dev / prod", "nombre de répliques par environnement"),
# ---------- conteneurs ----------
"containerd-crictl-ps":   ("containerd — Conteneurs actifs", "vue CRI du runtime"),
"containerd-systemdcgroup": ("containerd — Configuration", "pilote de cgroups systemd"),
"containerd-status":      ("containerd — Service systemd", "état, activation au démarrage, mémoire"),
"docker-build":           ("Docker — Construction de l'image", "Dockerfile multi-étapes durci"),
"docker-images-sizes":    ("Docker — Taille des images", "comparaison des images de service"),
"docker-inspect-user-health": ("Docker — Durcissement de l'image", "utilisateur non root et healthcheck"),
"docker-run-healthy":     ("Docker — Exécution locale", "conteneur signalé healthy par le runtime"),
# ---------- application ----------
"fastapi-root":           ("FastAPI — Point d'entrée", "réponse JSON du service users"),
"fastapi-readyz-vault":   ("FastAPI — Sonde de disponibilité", "état de la liaison Vault"),
"shared-logs-json":       ("Bibliothèque partagée — Logs JSON", "format de production"),
"shared-logs-plain-dev":  ("Bibliothèque partagée — Logs lisibles", "mode développement"),
"shared-fail-closed-local": ("Bibliothèque partagée — Fail-closed", "refus de démarrer sans secret en production"),
"instrumentator-metrics": ("Instrumentation — Métriques exposées", "compteurs et histogrammes Prometheus"),
# ---------- Vault ----------
"vault-status":           ("Vault — État du serveur", "initialisé, descellé, version"),
"vault-mounts-auth":      ("Vault — Moteurs et authentification", "KV v2 et méthode Kubernetes"),
"vault-policy-read":      ("Vault — Politique least-privilege", "droits accordés à users-service"),
"vault-kv-get":           ("Vault — Secrets du service", "clés présentes, valeurs masquées"),
# ---------- observabilite ----------
"prom-operator-cr":       ("Prometheus Operator — Instance", "rétention et état de la ressource"),
"prom-servicemonitors":   ("Prometheus — ServiceMonitors", "cibles déclarées dans le cluster"),
"ksm-metrics":            ("kube-state-metrics — Métriques", "état des pods et des déploiements"),
"am-rule-in-cluster":     ("Prometheus — Règles d'alerte", "PrometheusRule déployées"),
"grafana-dash-configmaps": ("Grafana — Dashboards as code", "tableaux de bord provisionnés en ConfigMaps"),
"elk-pods-running":       ("ELK — Composants", "Elasticsearch, Kibana, Logstash, Filebeat"),
"es-cluster-health":      ("Elasticsearch — Santé du cluster", "état, nœuds et shards"),
"es-cat-indices":         ("Elasticsearch — Index", "volumétrie des index quotidiens"),
"logstash-drop-proof":    ("Logstash — Filtrage des sondes", "les appels /livez ne sont pas indexés"),
# ---------- GitOps ----------
"argocd-apps-grid":       ("ArgoCD — Vue d'ensemble", "vingt Applications Synced et Healthy"),
"argocd-syncpolicy":      ("ArgoCD — Politique de synchronisation", "prune et selfHeal par Application"),
"argocd-project-yaml":    ("ArgoCD — AppProject", "dépôts, destinations et ressources autorisés"),
"argocd-events":          ("ArgoCD — Événements récents", "activité du contrôleur"),
"argocd-selfheal":        ("ArgoCD — Dérive détectée", "modification manuelle signalée OutOfSync"),
# ---------- qualite et securite ----------
"ruff-clean":             ("Ruff — Analyse statique", "version épinglée par la CI"),
"kubeconform-valid":      ("kubeconform — Validation des manifests", "filtres identiques à la CI"),
"conftest-pass":          ("Conftest — Politiques de sécurité", "soixante contrôles sur les manifests"),
"conftest-deny":          ("Conftest — Test négatif", "manifest non conforme rejeté"),
"threatmodel-reject":     ("Conftest — Modèle de menaces", "runAsNonRoot désactivé : déploiement refusé"),
"gitleaks-clean":         ("Gitleaks — Analyse du dépôt", "aucun secret détecté"),
"pipaudit-clean":         ("pip-audit — Dépendances Python", "aucune vulnérabilité connue"),
"pipaudit-detection":     ("pip-audit — Test négatif", "version vulnérable détectée, code de retour 1"),
"trivy-scan-local":       ("Trivy — Analyse de l'image", "vulnérabilités CRITICAL et HIGH"),
"trivy-blocked":          ("Trivy — Seuil bloquant", "image vulnérable, code de retour 1"),
"trivy-sbom":             ("Trivy — SBOM SPDX", "inventaire des paquets de l'image"),
"precommit-allfiles":     ("pre-commit — Hooks du dépôt", "exécution sur l'ensemble des fichiers"),
"precommit-fix":          ("pre-commit — Correction automatique", "espaces en fin de ligne supprimés"),
"terraform-tfstate-gitignore": ("Terraform — État hors du dépôt", "terraform.tfstate ignoré par Git"),
# ---------- exploitation ----------
"validate-platform-all":  ("Validation de la plateforme", "sept contrôles et bonus auto-réparation"),
"validate-platform-fail": ("Validation en mode bloquant", "service arrêté volontairement, code de retour 1"),
"validate-security-ok":   ("Validation de sécurité", "contrôles post-durcissement"),
"validate-selfheal":      ("Auto-réparation Kubernetes", "pod supprimé puis recréé"),
"smoke-e2e":              ("Test de bout en bout", "parcours fonctionnel complet"),
"checklist-weekly":       ("Checklist hebdomadaire", "contrôles d'exploitation"),
"ab-results":             ("Test de charge — ApacheBench", "débit et latences percentiles"),
"hpa-scaling-live":       ("Auto-scaling — État courant", "HPA et pods du service users"),
# ---------- scenarios ----------
"scenario1-03-ghcr-digest": ("Scénario 1 — Image déployée", "tag immuable et digest de l'image"),
"scenario1-05-rollout":   ("Scénario 1 — Déploiement progressif", "historique et pods du rollout"),
"scenario1-06-final-metrics": ("Scénario 1 — Service en production", "endpoints et métriques disponibles"),
"scenario2-01-before":    ("Scénario 2 — État initial", "readyz vert et endpoints peuplés"),
"scenario2-02-outage":    ("Scénario 2 — Vault indisponible", "readyz 503, endpoints vides, livez toujours vert"),
"scenario2-03-logs":      ("Scénario 2 — Journaux applicatifs", "échecs de lecture des secrets"),
"scenario2-04-recovery":  ("Scénario 2 — Retour à la normale", "secrets replantés, readyz 200"),
"scenario3-01-ratio80":   ("Scénario 3 — Consommation mémoire", "usage par conteneur"),
"scenario3-03-oomkill":   ("Scénario 3 — OOMKill", "conteneur tué par le noyau, code 137"),
"scenario4-01-scaleup":   ("Scénario 4 — Montée en charge", "le HPA porte le service de 2 à 4 répliques"),
"scenario4-03-scaledown": ("Scénario 4 — Descente en charge", "fenêtre de stabilisation de 300 secondes"),
"scenario4-04-pinned":    ("Scénario 4 — Décisions du HPA", "conditions et événements de redimensionnement"),
"scenario5-03-revert-sync": ("Scénario 5 — Retour arrière GitOps", "ArgoCD resynchronisé sur le commit de revert"),
"scenario5-04-recovered": ("Scénario 5 — Service rétabli", "endpoint applicatif de nouveau fonctionnel"),
"scenario6-01-onetime-token": ("Scénario 6 — Rotation du token", "valeur affichée une seule fois, masquée ici"),
"scenario6-02-rolling":   ("Scénario 6 — Redémarrage progressif", "propagation du nouveau secret"),
"scenario6-03-proof":     ("Scénario 6 — Vérifications finales", "readyz 200 et dépôt sans secret"),

# ---------- infrastructure as code ----------
"kvm-virsh-list":        ("Libvirt / KVM — Hyperviseur", "version, capacite du noeud, domaines declares"),
"kvm-qcow2-info":        ("QEMU — Image de base", "Ubuntu 22.04 cloud image au format qcow2"),
"reseau-libvirt":        ("Libvirt — Reseau virtuel", "reseau NAT, plage DHCP et pont"),
"vms-topologie":         ("Terraform — Topologie declaree", "domaines, volumes et disques cloud-init"),
"cloudinit-userdata":    ("cloud-init — Gabarit user-data", "utilisateurs, paquets et durcissement au boot"),
"cloudinit-ssh-hardening": ("cloud-init — Durcissement SSH", "mot de passe desactive, connexion par cle"),
"cloudinit-fail2ban":    ("cloud-init — Protection du noeud", "fail2ban, pare-feu et mises a jour"),
"ip-statique-dns":       ("cloud-init — Adressage reseau", "adresse statique, passerelle et resolveurs"),
"terraform-init":        ("Terraform — Initialisation", "providers telecharges et verrouilles"),
"terraform-plan":        ("Terraform — Plan d'execution", "16 ressources a creer, aucune destruction"),
"terraform-state-list":  ("Terraform — Versions verrouillees", "version du binaire et des providers"),
"terraform-inventory-gen": ("Terraform — Inventaire Ansible", "gabarit rendu par la ressource local_file"),
"ansible-playbook-start": ("Ansible — Plan d'execution", "plays et taches du playbook"),
"ansible-recap":         ("Ansible — Verification", "controle de syntaxe et hotes cibles"),
"ansible-dpkg-hold":     ("Ansible — Versions Kubernetes figees", "kubelet, kubeadm et kubectl en hold"),
"ansible-join-perms":    ("Ansible — Secret de jointure", "permissions restreintes sur le fichier kubeadm"),
"vault-token-rotation":  ("Vault — Rotation du token racine", "propagation dans les deux namespaces"),
"vault-readyz-after-rotation": ("Vault — Verification apres rotation", "services reconnectes, readyz 200"),
"scenario1-04-argocd-oos": ("ArgoCD — Ecart detecte", "commit pousse : Application OutOfSync avant synchronisation"),
"argocd-prune":          ("ArgoCD — Suppression automatique", "ressource retiree de Git, prune du cluster"),
"argocd-rollback": ("ArgoCD — Historique de deploiement", "chaque revision est un point de retour"),
"terraform-outputs": ("Terraform — Sorties declarees", "adresses des noeuds et inventaire, marquees sensitive"),
"filebeat-autodiscover": ("Filebeat — Decouverte automatique", "les logs d un pod recent sont indexes sans configuration"),
"fastapi-failclosed-crash": ("FastAPI — Demarrage fail-closed", "sans secret disponible, le service refuse de demarrer"),
"kyverno-policies":      ("Kyverno — Politiques d admission", "digest immuable et securite des conteneurs, en mode Audit"),
"am-hpa-firing":         ("HPA — Plafond atteint", "cinq repliques depuis quinze minutes, alerte declenchee"),
"ci-security-tab": ("Trivy — Publication du SARIF", "rapport produit, Code scanning non active sur le depot prive"),
"ci-environment-gate": ("GitHub — Environnement production", "declare par le workflow, approbateur a activer"),
}
